In [7]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

np.random.seed(42)  
A = np.random.randint(1, 101, size=100)

print("Array A:")
print(A)




Array A:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


In [8]:
np.mean(A)
print("\nStatistics of Array A:")
print("Minimum:", np.min(A))
print("Maximum:", np.max(A))
print("Median:", np.median(A))
print("Mean:", np.mean(A))
print("Standard Deviation:", np.std(A))



Statistics of Array A:
Minimum: 2
Maximum: 100
Median: 54.0
Mean: 51.54
Standard Deviation: 29.278463074417004


In [9]:
B = np.arange(100)
print("\nArray B:")
print(B)

print("Number of values in B:", B.size)



Array B:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Number of values in B: 100


In [10]:
zero_array = np.zeros((3, 4))
one_array = np.ones((3, 4))

print("\nZeros array:")
print(zero_array)
print("Shape:", zero_array.shape)
print("Data type:", zero_array.dtype)

print("\nOnes array:")
print(one_array)
print("Shape:", one_array.shape)
print("Data type:", one_array.dtype)

linear_array = np.linspace(0, 10, 7)

print("\nLinspace array:")
print(linear_array)


Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Data type: float64

Ones array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)
Data type: float64

Linspace array:
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


In [11]:

array_2d = np.arange(1, 13).reshape(3, 4)

print("\n2D Array:")
print(array_2d)

print("Shape:", array_2d.shape)
print("Number of dimensions:", array_2d.ndim)

# Indexing
print("Element at row 1, column 2:", array_2d[1, 2])

# Rows
print("First row:", array_2d[0, :])

# Columns
print("Second column:", array_2d[:, 1])

# Slicing
print("First two rows:")
print(array_2d[:2, :])

print("Last two columns:")
print(array_2d[:, 2:])


array_3d = np.arange(1, 25).reshape(2, 3, 4)

print("\n3D Array:")
print(array_3d)

print("Shape:", array_3d.shape)
print("Number of dimensions:", array_3d.ndim)

# Indexing
print("Element [0, 1, 2]:", array_3d[0, 1, 2])

# First 2D layer
print("First layer:")
print(array_3d[0])

# First row of first layer
print("First row of first layer:")
print(array_3d[0, 0, :])

# First column of first layer
print("First column of first layer:")
print(array_3d[0, :, 0])

# Slicing
print("First layer, first two rows:")
print(array_3d[0, :2, :])


2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Number of dimensions: 2
Element at row 1, column 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
First two rows:
[[1 2 3 4]
 [5 6 7 8]]
Last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]

3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Number of dimensions: 3
Element [0, 1, 2]: 7
First layer:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row of first layer:
[1 2 3 4]
First column of first layer:
[1 5 9]
First layer, first two rows:
[[1 2 3 4]
 [5 6 7 8]]


In [12]:

matrix = np.arange(1, 13).reshape(3, 4)

print("\nMatrix:")
print(matrix)

flattened = matrix.flatten()

print("\nFlattened array:")
print(flattened)


Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Task 2 - Vectorized Arithmetic and Linear Algebra

In [14]:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

addition = A + B

print("\nA + B:")
print(addition)

elementwise = A * B

print("\nA * B (element-wise):")
print(elementwise)

matrix_product = A @ B

print("\nA @ B (matrix multiplication):")
print(matrix_product)




Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A + B:
[[ 6  8]
 [10 12]]

A * B (element-wise):
[[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]


In [ ]:

transpose = A.T

print("\nTranspose of A:")
print(transpose)

det = np.linalg.det(A)

print("\nDeterminant of A:")
print(det)

if not np.isclose(det, 0):
    A_inv = np.linalg.inv(A)

    print("\nInverse of A:")
    print(A_inv)

    identity = A @ A_inv

    print("\nA @ A^-1:")
    print(identity)

    print("\nIs A @ A^-1 equal to identity matrix?")
    print(np.allclose(identity, np.eye(A.shape[0])))
else:
    print("\nA is not invertible.")


Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A^-1:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Is A @ A^-1 equal to identity matrix?
True
